### ISSUE TITLE
cost lots of cpu about this bitmapFont

### ISSUE THREAD

**Issue by sonygod** [Beeblerox/BitmapFont#1]
cost lots of cpu about this bitmapFont
in my  computer ,cpu is use more than 40%

**Comment by Beeblerox** [comment]
on which target?

**Comment by sonygod** [comment]
flash target

**Comment by Beeblerox** [comment]
ok. I think I can improve it.
And thank you for bug-report.

**Comment by Beeblerox** [comment]
I managed that main perfomance hit is from using:
- rapidly changing text property;
- fontScale (which affects the size of draw area);
- shadow and outline (which affects number of draw operations).

So, if you don't use there properties or use only static texts then perfomance should be satisfactory.

**Comment by Beeblerox** [comment]
I made some improvements in commit c4230cab92
Perfomance is much better now
