### ISSUE TITLE
Haxelib

### ISSUE THREAD

**Issue by impaler** [Beeblerox/BitmapFont#11]
Hey this is a wonderful class that would be helpful to nme developers as a haxelib. Haxeflixel could just have a dependency of that haxelib it looks like the same code? Cheers.

**Comment by Beeblerox** [comment]
@impaler I thought about placing this lib on haxelib and it could be a good idea :)
haxeflixel version is slightly different, so i'll leave it there

**Comment by impaler** [comment]
Ok cool, thats a shame you have to maintain both, I was wondering as I want to use it in my Omni-Components later these classes are great :)
