### ISSUE TITLE
BitmapTextAlign.RIGHT crops text when textfield.size not an integer

### ISSUE THREAD

**Issue by MiltonW** [Beeblerox/BitmapFont#17]
Neko, Linux are fine, but when testing Flash and HTML5:

textfield.size = 0.99;
![retro1](https://cloud.githubusercontent.com/assets/6236680/4408038/e6db064c-44cf-11e4-9b5f-c5102f1cee5c.png)

textfield.size = 1;
![retro2](https://cloud.githubusercontent.com/assets/6236680/4408043/ec2d2134-44cf-11e4-85ec-c9c80175bb5f.png)

I'm using the desyrel font: http://examples.phaser.io/_site/view_full.html?d=text&f=bitmap+fonts.js&t=bitmap%20fonts

**Comment by Beeblerox** [comment]
it isn't actually a bug. it is caused by the way bitmap text renders in blit mode: it have "canvas" bitmapdata on which text symbols are drawn.
If you want to "avoid" this problem then you can do it in two ways:
1) set textField's autoSize to true;
2) set textField's width to textField's textWidth

**Comment by MiltonW** [comment]
Hmm, autoSize is true by default, and setting it didn't make a difference.
Setting the width didn't help either. Exactly the same problem.

I don't understand what the canvas has to do with it? Why does 0.99 crop and 1.0 not?
The size attribute is Font size, not text size?

This is with what I actually use, works fine on Neko and Linux:
textfield = new BitmapTextField(font, "RETRO");
textfield.size = 0.57;
![retro3](https://cloud.githubusercontent.com/assets/6236680/4411275/469efb52-44ed-11e4-8f17-bc3ac6dabc7d.png)

**Comment by Beeblerox** [comment]
ok, i'll look into it this weekend

**Comment by Beeblerox** [comment]
@MiltonW can you try latest version?

**Comment by MiltonW** [comment]
Yep, fixed. Keep up the good work :)
