### ISSUE TITLE
lineSpacing - issue

### ISSUE THREAD

**Issue by Bigboer** [Beeblerox/BitmapFont#7]
I am trying to set the lineSpacing value after loading with loadAngelCode.
The line height does not seem to change, always stays the same.

**Comment by Bigboer** [comment]
Appologies this actually does work with your default .fnt file and png. It does not seem to have any effect when i use my .fnt file generated with Glyphdesigner. Any ideas what could be missing or something I need to check for?

**Comment by Beeblerox** [comment]
@Bigboer can you send me your .fnt and .png files for your font? Which version do you use (as3-blit, flixel-as3 or haxe)?
I think that problem might be in export options and I need to look in your export file. My implementation supports xml with some limitations (such as all symbols must be in one image file and with white color and transparent background).
I used Bitmap Font Generator v1.12 for font creation from http://www.angelcode.com/products/bmfont/ (for windows)
Plus it would be nice if you write sample code which introduces this problem. There is little chance that it's the source of problem.

**Comment by Bigboer** [comment]
Hi ZAphop

Attached are the files. I am using the as3-Blit version.. GlyphDesigner
1.5.5.
Thanks for the link to your font generator.. I have also edited your class
slightly to not use a default color..As my Glyphs have effects on them :)
Maybe an option to implement on your side as well.

Regards

Rw Liebenberg
Runtime Digital
website: www.runtime.co.za
email: rw@runtime.co.za
contact number: +27(0)83 380 0256

On Thu, Jul 5, 2012 at 4:49 PM, Zaphod <
reply@reply.github.com

**Comment by Bigboer** [comment]
Here sis my implementations

[Embed(source = "../assets/TestGlyph.fnt", mimeType =
"application/octet-stream")]
private var angelCodeFontData:Class;

 [Embed(source = "../assets/TestGlyph.png")]
private var angelCodeFontImage:Class;

var font2:PxBitmapFont = new
PxBitmapFont().loadAngelCode((newangelCodeFontImage()).bitmapData,
XML(
new angelCodeFontData()));

tf2 = new PxTextField(font2);

 tf2.y = 100;

this next line is the issue

tf2.lineSpacing = 2;

  addChild(tf2);

**Comment by Beeblerox** [comment]
@Bigboer sorry, but i don't see attached .fnt and .png files. maybe github refused them. you can send me them by email at zaphy@yandex.ru

**Comment by Beeblerox** [comment]
@Bigboer Changing output format from text to xml helped you?
